### PR TITLE
Form Validation Added

### PR DESCRIPTION
**Pull request by sanjay270899**
Issue #33 

image

Let me know if any changes needed. Thank You!

### CODE REVIEW

**Comment by sanjay270899** [comment]
Do add Level and DWOC Label before merging.
Also, if any changes needed then let me know.
Thank You.

**Comment by Tejas1510** [comment]
Great work @sanjay270899

**Comment by sanjay270899** [comment]
@Tejas1510, you haven't added labels before merging the PR?

**Comment by Tejas1510** [comment]
The issues are added corresponding label so we don't need to add for every pull request

**Comment by sanjay270899** [comment]
@Tejas1510, Labels are also compulsory for PR.

**Comment by sanjay270899** [comment]
Sorry for disturbing you but you forgot to add `DWOC` label.

**Pull request merged**
