### PR TITLE
fixes issue 314 creating error 404 page for website

### PR DESCRIPTION
**Pull request by Navdeepsingh4298**
issue #314 fixed. error 404 page works fine now.

### CODE REVIEW

**Comment by ChitvanRamani22** [comment]
@Navdeepsingh4298 can u please attach the ss of the work done.
Like how it looked earlier and how it is looking now. It becomes convient for the mentors to review.
Thanks

**Comment by Navdeepsingh4298** [comment]
Before this commit it was like this
image

now it looks like this 
image

**Comment by Navdeepsingh4298** [comment]
> @Navdeepsingh4298 can u please attach the ss of the work done.
> Like how it looked earlier and how it is looking now. It becomes convient for the mentors to review.
> Thanks

I've commented, have a look now. Is this fine?

**Comment by ChitvanRamani22** [comment]
@Navdeepsingh4298 instead of 0 can you use loader as it was shown in the template and second thing there is no requirement of go back button just one button at tge center to go home

**Comment by AmeyaJain-25** [comment]
> Before this commit it was like this
> image
> 
> now it looks like this
> image

@Navdeepsingh4298 Also can you share the URL at which it's showing 404.

Try these URLs /profile, /, /home, /abcd

And let us know that for which url, the 404 appears or how it is

**Comment by Navdeepsingh4298** [comment]
**Before changes or in live website it shows like this**

while accessing "/profile" it redirects to "/signin" after sometime and "/" is also redirecting to "/signin" 
image
image
image
image
image

**After changes**

while accessing "/profile" it redirects to "/signin" and "/" is also redirecting to "/signin"
image

while accessing "/home" and "/abcd" it redirects to error 404 page. or even trying to access any random page which is not mentioned in switch case that will redirected to error 404 page.
image
image
image

**Comment by AmeyaJain-25** [comment]
Perfect working @Navdeepsingh4298 
Nice work!!!

The issue is resolved 👍🏻

Just make the changes requested by @ChitvanRamani22 Mam.
And then it's ready for merge

**Comment by AmeyaJain-25** [comment]
Perfect working @Navdeepsingh4298 
Nice work!!!

The issue is resolved 👍🏻

Just make the changes requested by @ChitvanRamani22 Mam.
And then it's ready for merge

**Comment by Navdeepsingh4298** [comment]
should i commit now?

**Comment by AmeyaJain-25** [comment]
Yes sure.
Go ahead

**Comment by Navdeepsingh4298** [comment]
actually i've done requested changes.
changed 0 with loader
and remove other button to go back, now here is just one button to go home

**Comment by Navdeepsingh4298** [comment]
ok

**Comment by ChitvanRamani22** [comment]
Yeah @Navdeepsingh4298 as u have made the requested changes you can commit them now.

**Comment by Navdeepsingh4298** [comment]
i've commited

**Review by AmeyaJain-25 — APPROVED** [review]

**Comment by ChitvanRamani22** [comment]
@Navdeepsingh4298 amazing !! 
Keep contributing🥳

**Pull request merged**
