### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by codeaholic-shub**
Hey @AmeyaJain-25 ,
Kindly Review my PR ,
I have fixed the issue #299 !
codeaholic-shub_Athavani_ 😻 Athavani_Memories is a full-stack MERN Tool built in order to save all your memories in a single place and rejoice them through the years  - Google Chrome 12-06-2021 13_08_23

### CODE REVIEW

**Review by AmeyaJain-25 — APPROVED** [review]

**Comment by AmeyaJain-25** [comment]
Nice work @codeaholic-shub 🚀 
Keep Contributing

**Comment by AmeyaJain-25** [comment]
@Tejas1510 View the PR

**Comment by codeaholic-shub** [comment]
Hey @Tejas1510 ,
Kindly Review this PR ,
As it is approved !

**Review by Jassi10000 — APPROVED** [review]
Looks good !! ✌ @codeaholic-shub

**Comment by Jassi10000** [comment]
Thanks @codeaholic-shub for your contribution✌

**Pull request merged**
