### PR TITLE
Login Page to Center (Issue #338)

### PR DESCRIPTION
**Pull request by NOiR-07**

### CODE REVIEW

**Comment by AmeyaJain-25** [comment]
@NOiR-07 , Can you add the screenshot so that we can have a look to the work.

**Comment by NOiR-07** [comment]
**Shifted login page to centre**
Screenshot (1)

**Comment by heet-kumar** [comment]
@AmeyaJain-25  @NOiR-07  btw it differs browser to browser just this gye added margin-top but it is showing center to the Edge browser once see in Chrome or Brave browser it is no centered in that there it is not required of any margin-top without margin-top it looks god .

**Comment by NOiR-07** [comment]
okay

**Comment by AmeyaJain-25** [comment]
@NOiR-07 , @heet-kumar is right.
After seeing the change what you have done, the margin top is not the answer.
If you go with other resolutions, you will see the change in it. Just have a look in all the screen resolutions. 

And I think that margin top will not work. May be you can try flex box or viewport height, etc.

**Comment by NOiR-07** [comment]
> @NOiR-07 , @heet-kumar is right.
> After seeing the change what you have done, the margin top is not the answer.
> If you go with other resolutions, you will see the change in it. Just have a look in all the screen resolutions.
> 
> And I think that margin top will not work. May be you can try flex box or viewport height, etc.

sure, I will try to use better approach

**Review by Jassi10000 — CHANGES_REQUESTED** [review]
@NOiR-07  Buddy , try to make its width : 100% and margin : auto 
if you confused , then try this basic approach 
But what I would suggest is the same as others , to use flexbox , it will become very easy for you nd the responsiveness feature will not be a great concern

**Comment by NOiR-07** [comment]
> @NOiR-07 Buddy , try to make its width : 100% and margin : auto
> if you confused , then try this basic approach
> But what I would suggest is the same as others , to use flexbox , it will become very easy for you nd the responsiveness feature will not be a great concern

Okay will do it in 1-2 days when I'll get free

**Comment by Jassi10000** [comment]
> > @NOiR-07 Buddy , try to make its width : 100% and margin : auto
> > if you confused , then try this basic approach
> > But what I would suggest is the same as others , to use flexbox , it will become very easy for you nd the responsiveness feature will not be a great concern
> 
> Okay will do it in 1-2 days when I'll get free

@NOiR-07  Any updates ?

**Comment by ChitvanRamani22** [comment]
@NOiR-07 do you want to work on this further?

**Comment by NOiR-07** [comment]
> @NOiR-07 do you want to work on this further?

I'm not able to fix it, i tried flexbox though

**Pull request closed without merging**
