### PR TITLE
header background changed

### PR DESCRIPTION
**Pull request by Khimit**
#38 @Tejas1510  header background changed

### CODE REVIEW

**Comment by Khimit** [comment]
@Tejas1510 please review my PR

**Comment by Tejas1510** [comment]
Great Work @Khimit

**Comment by Khimit** [comment]
@Tejas1510  Thanks for compliment.

**Comment by Khimit** [comment]
@Tejas1510 please add releated labels like levels and others along with DWoC label to this PR.

**Comment by Khimit** [comment]
@Tejas1510 thanks ... But can you add same label of **level 2** that you added in the same issue

**Pull request merged**
