### PR TITLE
improved the background image of login page

### PR DESCRIPTION
**Pull request by ranasauravsingh**
- Improvised the background image with responsiveness of the login page.

### CODE REVIEW

**Comment by sanjay270899** [comment]
@ranasauravsingh Background Image is been changed for whole application.

image

**Comment by sanjay270899** [comment]
Also, tell me honestly, which one is looking better?
image

**Comment by Tejas1510** [comment]
@ranasauravsingh thanks for your contribution
 the background image doesn't go good with the complete layout of the project, it is very loud like the main attention is drawn to the background rather than the main content
If you see the background of Instagram, Facebook, Linkedin they are very light, and support the entire layout very well
So you can think on it and do the required changes
The UI should look very profesional

**Comment by ranasauravsingh** [comment]
Yeah sir... I get the point that the image is distracting rather than elaborating the project... Thank You @sanjay270899 sir for the guidance... 
I have a another pic also with can you just have look...
memories

**Pull request closed without merging**
