### PR TITLE
create separate sidebar component and add some styles

### PR DESCRIPTION
**Pull request by Navdeepsingh4298**
fixes issue #305 
____________________________________________________________________________________________________________________________________
First one Before changes and Second one After changes:->

image

When clickes on any option in sidebar it persist that style.
-----------------------------------------------------------------------------------

image

When i clicked on create memory option it shows like below:
-----------------------------------------------------------------------------------

image
image

### CODE REVIEW

**Comment by ChitvanRamani22** [comment]
@Navdeepsingh4298 i could observe that the 404 page is not responsive.

**Comment by Navdeepsingh4298** [comment]
i'll fix responsiveness. is sidebar fine now?

**Comment by Navdeepsingh4298** [comment]
i've done fix responsiveness issue now it looks like below:
------------------------------------------------------------------------------------------------------------------------
image
image

------------------------------------------------------------------------------------------------------------------------
* there is one problem i can't be able to change size of loader dynamically according to media query.

**Comment by Navdeepsingh4298** [comment]
image
image
image

this is how it looks like in different sizes 
But i'm unable change size of loader can you help me with this?

**Comment by Navdeepsingh4298** [comment]
@ChitvanRamani22 
i'm sorry to tag you but i want to fix this issue as soon as possible. because i'm going to have my exams very soon.
So, tell me what to do? have a look and also tell me what to do with loader situation. as i can't be able to change its size dynamically.

**Comment by AmeyaJain-25** [comment]
Really awesome work @Navdeepsingh4298 
It maintained the theme too.

I think everything is good.
@ChitvanRamani22 , just have a look to it and merge if everything is good.

**Comment by ChitvanRamani22** [comment]
@Navdeepsingh4298 thanks for your efforts.
Keep contributing🥳

**Review by ChitvanRamani22 — APPROVED** [review]

**Pull request merged**
