### PR TITLE
added feature-Send random post on Mail every week

### PR DESCRIPTION
**Pull request by Ashuto7h**
issue #30   

## Type of change

- [ ] New feature (non-breaking change which adds functionality to send a random memory as mail to subscribed users.)

### Description of changes 
* On the client-side, there is a form just below the create memory form, where any subscriber can enter his email. the form doesn't validate the email field for now.
* On the server-side, the email is stored in a new schema MailSubscriber, from where emails are fetched later.

### Packages added
* node-cron
* nodemailer

### Instructions for files changed or added.
`client/src/api/index.js` 
change the variable urlMail according to your API URL

`server/.env.example`
the .env file now also includes the mail and password of the sender.

`server/scripts/mailSender.js`
while sending mail, you can get into an error if you are using Gmail or any other mail service which prevents unauthorized access to your account. to prevent this for Gmail, check [stackoverflow](https://stackoverflow.com/a/41862069). follow the two links provided here and give access to your account.

### What's Next
currently, the mail contains a JSON object of the post only.  I will render it in form of HTML in the later pull request.

# Checklist:

- [ ] My code follows the style guidelines(Clean Code) of this project
- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by Tejas1510** [comment]
Excellent Work @Ashuto7h 
I have gone through the entire code and I can see the amount of hard work put to make it
This is what call a real open source contribution
Great Work

**Comment by Ashuto7h** [comment]
> Excellent Work @Ashuto7h
> I have gone through the entire code and I can see the amount of hard work put to make it
> This is what call a real open source contribution
> Great Work

Thanks for the compliments

**Comment by Tejas1510** [comment]
@Ashuto7h 
var transporter = nodemailer.createTransport({
        service: 'gmail',
        auth: {
            user: process.env.MAIL,
            pass: process.env.PASS
        }
    });

Can you tell from which website or from where we have to get MAIL and PASS so other will find it easy

**Comment by Ashuto7h** [comment]
If you are going to host it, you should use your own domain mail service or You can use any mail client but don't share your mail and pass with others.

**Comment by Tejas1510** [comment]
Thanks for info @Ashuto7h

**Comment by Tejas1510** [comment]
@Ashuto7h the current format of the mail sent is simple HTML which doesn't look good
So do you want to work on improving the staying of the message sent, I will create a new issue

**Comment by Ashuto7h** [comment]
Yes I will work on it

**Pull request merged**
