### PR TITLE
added animation to posts

### PR DESCRIPTION
**Pull request by Castella1313**
issue solved #180 

How it looks now - 

https://user-images.githubusercontent.com/53293156/114079754-34b39e80-98c8-11eb-8cb4-06b61adfd39e.mov

### CODE REVIEW

**Comment by Castella1313** [comment]
@Tejas1510 It was soooo hard to find the the component from the whole pool of code 😅

**Comment by Castella1313** [comment]
@Tejas1510 @sanjay270899 May you please review my PR!

**Review by sanjay270899 — CHANGES_REQUESTED** [review]
@Castella1313 Can you please un-staged `client/package-lock.json` and `client/yarn.lock` files?

**Comment by Castella1313** [comment]
@sanjay270899 Are they unstaged now?

**Comment by sanjay270899** [comment]
@Castella1313 Not yet.

**Comment by Castella1313** [comment]
@sanjay270899 Can you please tell me how to do it ?

**Comment by Castella1313** [comment]
@sanjay270899 I think its done now!

**Comment by Castella1313** [comment]
@sanjay270899 @Tejas1510 Can you please check it now?

**Comment by sanjay270899** [comment]
@Castella1313 No, you have removed those file. Join Athavani's discord server, I will try to hep. https://discord.com/invite/gEqSYzc5Yu

**Comment by Castella1313** [comment]
@sanjay270899 Can you please check it now?

**Comment by sanjay270899** [comment]
@Castella1313 Yes, it is fine now. Do same for package-lock.json in server folder.

**Comment by Castella1313** [comment]
@sanjay270899 Done

**Review by sanjay270899 — APPROVED** [review]
Great!

**Comment by Castella1313** [comment]
@sanjay270899 Can you add the level?

**Comment by sanjay270899** [comment]
@Castella1313 Oh Sorry! I forgot to add labels. Added now.

**Pull request merged**
