### PR TITLE
Added text in loading screen

### PR DESCRIPTION
**Pull request by Hardikpoudel**
The loading bar in the home screen is replaced with some text

### CODE REVIEW

**Review by Jassi10000 — CHANGES_REQUESTED** [review]
@Hardikpoudel Some files are conflicting
It would be nice if you resolve those conflicts first

**Comment by Jassi10000** [comment]
> @Hardikpoudel Some files are conflicting
> It would be nice if you resolve those conflicts first

@Hardikpoudel Any updates on this  ?

**Comment by AmeyaJain-25** [comment]
@Hardikpoudel 
Resolve the conflict and push again so that we can merge

**Comment by Jassi10000** [comment]
@Hardikpoudel Closing this buddy as its been a long time since you have been assigned and there's no activity after we requested changes

**Comment by ChitvanRamani22** [comment]
@Jassi10000 he just asked for the meet tomorrow and we scheduled it for tomorrow morning.
I think thi deletion of so many lines would effect the repo

**Comment by Jassi10000** [comment]
How it can be changed @ChitvanRamani22 , we haven't merged the PR , so it can't effect the main repo till its merged
Anyways , as you are saying that you have a meet with him , am opening it again

**Comment by ChitvanRamani22** [comment]
> I don't think so that it can be changed @ChitvanRamani22 , we haven't merged the PR , so it can't effect the main repo till its merged
> Anyways , as you are saying that you have a meet with him , am opening it again 
@Jassi10000 sorry there was a misconception from my side i thought i has been merged and closed

**Comment by Jassi10000** [comment]
> > I don't think so that it can be changed @ChitvanRamani22 , we haven't merged the PR , so it can't effect the main repo till its merged
> > Anyways , as you are saying that you have a meet with him , am opening it again
> 
> @Jassi10000 sorry there was a misconception from my side i thought i has been merged and closed

No issues @ChitvanRamani22

**Comment by Jassi10000** [comment]
@ChitvanRamani22 I hope you had that meeting with the contributor still there is no progress since last week on this , so closing this

**Pull request closed without merging**
