### PR TITLE
Changed the whole code according to Authentication Code

### PR DESCRIPTION
**Pull request by sanjay270899**
Issue #69 

⚡ Here is the new Athavani Website.

✨ Some new features and changes:

- Changed the Post Model structure.
- Now, the user has to log in before accessing the Main Page of the website.
- User can now like or dislike a particular post just once.
- User can edit the post which belongs to them only.
- Fixed dislike button.
- Edited .env.example file.

- SignUp
image

- SignIn
image

- HomePage
image

### CODE REVIEW

**Comment by sanjay270899** [comment]
@Tejas1510 You have to remove all old posts from your DB, as the structure of the Post is changed.

**Comment by Tejas1510** [comment]
@sanjay270899 The login method is not working properly and is giving 404 error

**Comment by sanjay270899** [comment]
@Tejas1510 can you show me a screenshot of it. Or can we discuss this over discord? Because it is working perfectly from my side.

**Comment by sanjay270899** [comment]
@Tejas1510, have you updated .env file in your local project? You have to add a new key with the name `JWT_KEY`.

**Comment by Tejas1510** [comment]
@sanjay270899 can you send me simple hi message on discord

**Pull request merged**
