### PR TITLE
added dark mode

### PR DESCRIPTION
**Pull request by mohammedjameel24**
## Issue 
Dark mode 
## fix
ADDED Dark Mode
## files changed 
client -> public -> index.html

## Context
pure java script implementation

### CODE REVIEW

**Comment by mohammedjameel24** [comment]
please merge my pull request

**Comment by Tejas1510** [comment]
@mohammedjameel24 why have you changed the nodemodule folder

**Comment by mohammedjameel24** [comment]
> @mohammedjameel24 why have you changed the nodemodule folder

Some packages needed npm --upgrade audit fix fund

**Review by sanjay270899 — CHANGES_REQUESTED** [review]
Why you have made `node_modules` folder on root folder?

**Comment by mohammedjameel24** [comment]
Removed nodemodules that were accidentally created @Tejas1510

**Comment by mohammedjameel24** [comment]
Merge?

**Comment by sanjay270899** [comment]
@mohammedjameel24 Sorry for the delay. But can you please provide us the screenshot of it?

**Comment by mohammedjameel24** [comment]
Ok

**Comment by mohammedjameel24** [comment]
Athavani1
## After
Athavani

**Comment by mohammedjameel24** [comment]
please review and merge my pull request @Tejas1510 @sanjay270899

**Comment by Tejas1510** [comment]
@mohammedjameel24 https://css-tricks.com/a-complete-guide-to-dark-mode-on-the-web/
Refer to this website to improve the gradient Color Layout

**Pull request closed without merging**
