### PR TITLE
Divided header in two parts

### PR DESCRIPTION
**Pull request by Cgoyal48**
Hey @sanjay270899 Please check the PR, I have divided the header into two parts.

### CODE REVIEW

**Comment by sanjay270899** [comment]
@Cgoyal48 please resolve the conflicts.

**Comment by sanjay270899** [comment]
Also, can you please add a screenshot?

**Comment by Cgoyal48** [comment]
@sanjay270899 Please check the PR, conflict has been resolved.

**Comment by sanjay270899** [comment]
@Cgoyal48 Yes, conflicts are not resolved. Can you please now provide a screenshot?

**Review by sanjay270899 — APPROVED** [review]

**Comment by Tejas1510** [comment]
@sanjay270899 if you think the work is fine you can merge the full request

**Pull request merged**
