### PR TITLE
Footer added

### PR DESCRIPTION
**Pull request by Ankita297**
Enhancement of the footer

### CODE REVIEW

**Comment by Ankita297** [comment]
Athavani - Google Chrome 31-03-2021 13_33_54
Athavani - Google Chrome 31-03-2021 14_33_19

**Review by sanjay270899 — APPROVED** [review]
Great!

**Comment by Ankita297** [comment]
@sanjay270899 Sir you hav enot added GSSoc level label ?

**Comment by Ankita297** [comment]
@sanjay270899 Sir you have not added GSSoC level label ?

**Comment by Ankita297** [comment]
Can You please add it now ?

**Comment by sanjay270899** [comment]
@Ankita297 Sorry, I forgot to add 😅. Added now.

**Pull request merged**
