### PR TITLE
Authentication Backend and Frontend

### PR DESCRIPTION
**Pull request by sanjay270899**
Issue #6 

**Frontend**:
- Sign In
image
- Sign Up
image

**Backend**
- Sign In
image
- Sign Up
image

### CODE REVIEW

**Comment by sanjay270899** [comment]
After adding authentication, I have to go through the whole code to fix it according to the newly changed code. Should I make a new issue about this and solve this? @Tejas1510

**Comment by Tejas1510** [comment]
Go ahead @sanjay270899 just create a new Issue but this PR which you have generated will have issue 4 and the other PR you will generate after complete creation of App with proper authentication will have level-5

**Comment by sanjay270899** [comment]
@Tejas1510 OK 👍

**Comment by Tejas1510** [comment]
@sanjay270899 I have revied the complete code and I have just one word Awesome
Great Work, I can see the amount of work Done
Kudos 
This is the true meaning of Open Source

**Pull request merged**
