### PR TITLE
Crappy Design

### PR DESCRIPTION
**Pull request by ayushkwal**
I have changed design of footer and removed toast and presenting toast data inside form itself.

### CODE REVIEW

**Comment by ChitvanRamani22** [comment]
@ayushkwal appreciate your efforts.
But can you please have a look at this.

**Comment by ayushkwal** [comment]
Hmmm... That's strange! I will fix that and will pull again.

**Comment by ChitvanRamani22** [comment]
@ayushkwal dont create a new pr just commit the changes in this pr itself.

**Comment by ayushkwal** [comment]
Hi Again,
Now, it's working fine and looking good.
It may be possible that something won't work due to continuous contributions by other users. I will resolve that in next time.

**Comment by ChitvanRamani22** [comment]
> Hi Again,
> Now, it's working fine and looking good.
> It may be possible that something won't work due to continuous contributions by other users. I will resolve that in next time.  
> 

But you need to resolve merge conflicts and also look at the checks.
Without this merging is not possible.

**Comment by ayushkwal** [comment]
Well from my side, everything's working fine. You can check it too.

**Comment by ayushkwal** [comment]
I have resolved the conflicts. Hope, it will work!

**Comment by ayushkwal** [comment]
Hi, Have you merged it?

**Comment by ChitvanRamani22** [comment]
@ayushkwal u would have recieved a mail if it would hve been merged .
@Tejas1510 sir will first look at the checks.

**Comment by ayushkwal** [comment]
Thankyou very much🥳🥳

**Pull request merged**
