### PR TITLE
issue #158-Show Password - feature

### PR DESCRIPTION
**Pull request by pratyushchamola**
**AIM**
to address issue #158 , and allow the user to view his password.

final screenshot:
pull ss

**Changes made in following files:**

client/src/components/Auth/SignUp/SignUp.js
client/src/components/Auth/SignUp/SignUp.module.css

### CODE REVIEW

**Comment by sanjay270899** [comment]
@pratyushchamola Great! Looks go to me.

@Tejas1510 Pratyush is using `npm7x` version, so due to that, `lockfileVersion` in `package.json` is udapte to `2` from `1`.
Now, my doubt is, whether it will effect the users who are using `npm6x` version?

**Comment by Tejas1510** [comment]
Most of the user or even I am using version 6 so I think so it will cause a issue as some dependencies may or may not be supported by  version 7
@sanjay270899

**Comment by sanjay270899** [comment]
@pratyushchamola can you please remove `client/package-lock.json`, `server/package-lock.json` and `client/yarn.lock` files from commit?

**Comment by pratyushchamola** [comment]
@sanjay270899 sure

**Comment by sanjay270899** [comment]
@pratyushchamola You don't have to delete those files... We need those files. Just convert them back as they were before. And then send PR. Got it?

**Comment by pratyushchamola** [comment]
@sanjay270899 Oh, sorry!, got a little confused. It's good that I am facing such problems with my first PR, it would be really helpful for me afterwards , and also thank you for your guidance.
I would now make a new PR, with the suggested changes.

**Comment by Tejas1510** [comment]
@pratyushchamola Great 
This should be the spirit for open source

**Comment by sanjay270899** [comment]
@pratyushchamola No need to make new PR.
You can do the following:

1. Remove last 3 commits: `git reset --hard HEAD~3`
2. Remove last 4th commit but keep changes: `git reset --soft HEAD^`
3. Now, un-stage those 3 files. `git reset client/package-lock.json` `git reset client/yarn.lock` `git reset server/package-lock.json`
4. Add new commit.
5. Then push the changes forcefully: `git push --force origin <branchName>`

**Comment by pratyushchamola** [comment]
@sanjay270899 thank you so much mentor,  I too was trying the above procedure but, somehow I mixed-up the first two steps, so instead thought of making a  [new PR](https://github.com/Tejas1510/Athavani/pull/162), I hope this is fine with the mentors, else I would proceed as instructed.

**Comment by sanjay270899** [comment]
PR #162

**Pull request closed without merging**
