### PR TITLE
Added logo and animated logo

### PR DESCRIPTION
**Pull request by antaramunshi**
https://user-images.githubusercontent.com/74422097/103192369-6e0a6480-48fe-11eb-8bbf-b1b0a2548c2b.mp4

Athavani logo

### CODE REVIEW

**Comment by Tejas1510** [comment]
@antaramunshi the logo looks good
But can you make it depict the idea of the project which is memories

**Comment by antaramunshi** [comment]
The shutter depicts the memories so ig i added that

**Comment by Tejas1510** [comment]
The Video looks good and we will use that in the readme
But bring something different which exactly depict something related to memory
Awesome Work on Video

**Comment by antaramunshi** [comment]
Athavani (1)
Please check whether this works?

**Comment by Tejas1510** [comment]
@antaramunshi I am Taking Your video
For the logo, we have other entries so we will be considering that
It doesn't mean your logo is not good but others have come with another idea 
Just Create a new Pull reguest where you add the video in a folder named assets which is inside the homepage folder and make a PR
I will merge that

**Pull request closed without merging**
