### PR TITLE
Added the code for firebasae login

### PR DESCRIPTION
**Pull request by ritik-vashist**
This is i regard to #301.

I request @AmeyaJain-25 sir to please review my work and give your valuable feedback.

### CODE REVIEW

**Comment by ChitvanRamani22** [comment]
@ritik-vashist why have you commented the code?

**Comment by ritik-vashist** [comment]
@ChitvanRamani22  ma'am because as per the present code we are passing the token from backend to frontend but the code has not been designed to handle bearer token so as per talks between @AmeyaJain-25 sir and @Tejas1510 sir they suggested me to do this in this issue and work on the rest part latter.

**Comment by ritik-vashist** [comment]
Bearer token means the token which is generated by firebase-admin for the user.

**Comment by AmeyaJain-25** [comment]
> @ritik-vashist why have you commented the code?

Yes @ChitvanRamani22 ,
I and @Tejas1510 sir had a talk about this.

If we use firebase, then we need to shift completely over there. And for right now, we shouldn't, because other participants may get confused and not understand.
So, the functionality is written properly by Ritik, only the thing is that it's commented so that when we shift to firebase, we can uncomment and re work on it

**Comment by ChitvanRamani22** [comment]
@AmeyaJain-25 okay fine...
Great work @ritik-vashist !

**Comment by ritik-vashist** [comment]
Thank you @ChitvanRamani22 ma'am.

**Review by AmeyaJain-25 — APPROVED** [review]

**Pull request merged**
