### PR TITLE
Added dark mode

### PR DESCRIPTION
**Pull request by itsIapetus**
Closes issue #118

### CODE REVIEW

**Comment by sanjay270899** [comment]
@itsIapetus Sorry, but this is not the main website. Our website is in Reactjs.

**Comment by sanjay270899** [comment]
@itsIapetus Text is not readable in dark mode.
image

**Comment by itsIapetus** [comment]
Okay, I will change that.

**Comment by sanjay270899** [comment]
@itsIapetus Any update?

**Comment by itsIapetus** [comment]
@sanjay270899 Actually I had my MTEs, will do this tomorrow for sure, sorry about the delay.

**Comment by sanjay270899** [comment]
@itsIapetus any update?

**Pull request closed without merging**
