### PR TITLE
Forgot Password Backend

### PR DESCRIPTION
**Pull request by sanjay270899**
Issue #75 

✨ Forgot Password Feature Implemented on the backend side.

- Modified User Model (one `resetPassLink` attribute added)
- Authentication routes updated (two new routes added i.e. `/forgot` & `/reset-password`)
- Authentication controllers updated (two new controllers added i.e. `forgot` & `resetPassword`)
- _.env_ example file updated (two new environment variables added i.e. `RESET_PASSWORD_JWT_KEY` & `CLIENT_URL`)

**Screenshots Time** 😅

- Mail for the reset link
image

- `/auth/forgot` API
image

- `/auth/reset-password` API
image

### CODE REVIEW

**Comment by Tejas1510** [comment]
As always Good Work @sanjay270899

**Comment by Tejas1510** [comment]
@sanjay270899 You haven't added the Client Side Code where when the user click on forget password then something should happen

**Comment by Tejas1510** [comment]
So the current merge Pull Request won't be considered 
Just make a new PR adding the required changes and I will merge that and add corresponding labels

**Comment by sanjay270899** [comment]
@Tejas1510 on Issue #75 only backend label was there, and also, it was of level-3, so I thought that I have to do it in two separate PRs.

**Comment by Tejas1510** [comment]
Ok Don't Worry I will increase the level of points
You can start working

**Pull request merged**
