### PR TITLE
Added hover on social icons.

### PR DESCRIPTION
**Pull request by supzi-del**
#295 
Please check if I have added the code to the correct folder.

### CODE REVIEW

**Review by AmeyaJain-25 — APPROVED** [review]

**Review by Jassi10000 — COMMENTED** [review]
@supzi-del It would be nice if you put screenshots of how it was earlier and how it's now at present , it will be easy for both you and us to see the changes and evaluate them .

**Comment by supzi-del** [comment]
Before: when hovered
Screenshot (184)
Now: when hovered
Screenshot (182)

**Comment by Jassi10000** [comment]
> Before: when hovered
> Screenshot (184)
> Now: when hovered
> Screenshot (182)


@supzi-del Looks better , but I want to confirm one thing that this effect works of every one of those 4 icons ?

**Comment by supzi-del** [comment]
@Jassi10000 Yes applicable to all 4 icons.

**Comment by supzi-del** [comment]
https://user-images.githubusercontent.com/78655439/121948759-48223080-cd75-11eb-923a-7d8ed4e6d551.mp4

**Review by Jassi10000 — APPROVED** [review]
Now it looks and works much much better !!!!

**Comment by Jassi10000** [comment]
Thanks @supzi-del for your contribution✌

**Pull request merged**
