### PR TITLE
bug fixed post update

### PR DESCRIPTION
**Pull request by sanskarbansal**
Fixes:  #320 

User was able to update other user's post earlier (fixed).

### CODE REVIEW

**Comment by rushikadivar** [comment]
Hey Sanskar can you explain to me how you did you get all the memories post based on the user, because in my case it doesn't even sign in or sign up so if am not getting in I'll not able to see the memories post.

**Comment by sanskarbansal** [comment]
@rushikadivar so you are not able to initialise this project on your localhost? Please correct me if i am wrong.

**Comment by rushikadivar** [comment]
> @rushikadivar so you are not able to initialise this project on your localhost? Please correct me if i am wrong.

Exactly, something like that. can I show your .env file because I think the problem should be there in my case.

**Review by ChitvanRamani22 — APPROVED** [review]

**Comment by sanskarbansal** [comment]
@rushikadivar 
1. Obtain OAuth 2.0 credentials (Client_Id & Client_Secrete) from the Google API Console .
2. Go To [OAuthPlayground](https://developers.google.com/oauthplayground), Click on settings, Tick "Use your own OAuth credentials". 
3. Paste you client id and client secrete in appropriate boxes. 
4. In "Select & authorize APIs" section type "https://mail.google.com" in "Input your own scopes field" & Click "Authorize APIs"
5. Click "Exchange authorization code for tokens"
6. Copy and paste this refresh token in your .env file
7. Paste Client_id and Client_secrete which you got in Step 1 in your .env file. 
8. I guess that's it. 
Please let me know if you still face any issue.

**Comment by rushikadivar** [comment]
Thanks Sanskar, mistake was on refresh token and access token that's why I was facing problems. Thanks for your help

**Comment by ChitvanRamani22** [comment]
@sanskarbansal great work!
Thanks for the efforts.

**Pull request merged**
