### PR TITLE
homepage basic added

### PR DESCRIPTION
**Pull request by ShambhaviSharma0110**
I've added a basic homepage folder and a navbar folder.
react-scripts weren't working so I've installed that as well.

### CODE REVIEW

**Comment by sanjay270899** [comment]
@ShambhaviSharma0110 Please provide a screenshot of it...

**Comment by sanjay270899** [comment]
@ShambhaviSharma0110 Can you please un-staged `client/package-lock.json` and `client/yarn.lock` files?

**Comment by ShambhaviSharma0110** [comment]
> @ShambhaviSharma0110 Can you please un-staged `client/package-lock.json` and `client/yarn.lock` files?

should I just remove those files?

**Comment by sanjay270899** [comment]
> > @ShambhaviSharma0110 Can you please un-staged `client/package-lock.json` and `client/yarn.lock` files?
> 
> should I just remove those files?

No, you don't have to remove those files. You have to reset those files as they were before.

**Comment by sanjay270899** [comment]
You can do the following:

1. Remove last 2 commits: `git reset --hard HEAD~2`
2. Remove last 3rd commit but keep changes: `git reset --soft HEAD^`
3. Now, un-stage those 2 files. `git reset client/package-lock.json` and `git reset client/yarn.lock`
4. Add new commit.
5. Then push the changes forcefully: `git push --force origin <branchName>`

**Comment by ShambhaviSharma0110** [comment]
> You can do the following:
> 
> 1. Remove last 2 commits: `git reset --hard HEAD~2`
> 2. Remove last 3rd commit but keep changes: `git reset --soft HEAD^`
> 3. Now, un-stage those 2 files. `git reset client/package-lock.json` and `git reset client/yarn.lock`
> 4. Add new commit.
> 5. Then push the changes forcefully: `git push --force origin <branchName>`

done! thanks a lot for the help!

**Comment by sanjay270899** [comment]
@ShambhaviSharma0110 There is no new changes in this PR. I think you have missed some steps or something wrong has happened. How can I help you?

**Comment by sanjay270899** [comment]
@ShambhaviSharma0110 Create a new PR if you are facing any problem.

**Pull request closed without merging**
