### PR TITLE
Improved the UI of Create memory form

### PR DESCRIPTION
**Pull request by ambalika24**
@AmeyaJain-25 Sir, i have improved the UI of create memory form, kindly check the PR.

### CODE REVIEW

**Comment by ChitvanRamani22** [comment]
@ambalika24 can you please add the ss of the earlier one and the one which u have designed.
Would be really helpful.
Thanks

**Comment by ChitvanRamani22** [comment]
@ambalika24 how did it earlier look like?

**Comment by ambalika24** [comment]
Sir earlier the form looked like this-
or
and after my final design is-
newform

**Comment by ChitvanRamani22** [comment]
@ambalika24 ATM the earlier background-color suits more on our theme. And secondly i am a girl😅
@AmeyaJain-25 WDYT?

**Comment by AmeyaJain-25** [comment]
> @ambalika24 ATM the earlier background-color suits more on our theme. And secondly i am a girl😅
> @AmeyaJain-25 WDYT?

I think it's fine.
Because the sidebar ia also coming in light black.
I think we can keep it white. Once the background is done and sidebar is done, we can change the color.

Other than color, the UI is awesome. Also the shadow effects, etc are good.
Nice work @ambalika24 

I'm done with the review @ChitvanRamani22 .
Once you approve this, just merge it.

**Review by AmeyaJain-25 — APPROVED** [review]

**Comment by ChitvanRamani22** [comment]
@ambalika24 great work!!
Thanks for your efforts.
Keep contributing.

**Review by ChitvanRamani22 — APPROVED** [review]

**Comment by ambalika24** [comment]
> @ambalika24 ATM the earlier background-color suits more on our theme. And secondly i am a girl😅
> @AmeyaJain-25 WDYT?



> @ambalika24 ATM the earlier background-color suits more on our theme. And secondly i am a girl😅
> @AmeyaJain-25 WDYT?

Okay, sorry ma'am 😅

**Comment by ambalika24** [comment]
> > @ambalika24 ATM the earlier background-color suits more on our theme. And secondly i am a girl😅
> > @AmeyaJain-25 WDYT?
> 
> I think it's fine.
> Because the sidebar ia also coming in light black.
> I think we can keep it white. Once the background is done and sidebar is done, we can change the color.
> 
> Other than color, the UI is awesome. Also the shadow effects, etc are good.
> Nice work @ambalika24
> 
> I'm done with the review @ChitvanRamani22 .
> Once you approve this, just merge it.

Thank you Sir!!

**Pull request merged**
